version: '3'
services:
  app:
    command: sh -c "npm install -g nodemon && (npm run dev -- -p $PORT & nodemon -w package-lock.json --exec 'npm install')"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
