export const PIECE_BASE_PRICE = 30;
export const PIECE_PRICE_PER_ADULT = 3;
export const PIECE_PRICE_PER_CHILD = 4;
export const PIECE_PRICE_PER_DOG = 4;
export const PIECE_PRICE_PER_NON_FLYING_BIRD = 5;
export const PIECE_PRICE_PER_FLYING_BIRD = 7;
export const PIECE_PRICE_PER_SUBJECT_COMING_AND_GOING = 6;
